### ISSUE TITLE
AssertionError when generating pseudo labels

### ISSUE THREAD

**Issue by YukangWang** [valeoai/xmuda#13]
Hi, I'm currently using my own dataset as the target. Since this dataset is unlabeled, I modify the related files and finally run `train_xmuda.py` sucessfully. But when I try to generate pseudo labels, I encounter an AssertionError at:
https://github.com/valeoai/xmuda/blob/8b39f8f77f048cd4c086323dd89fbf9710335d35/xmuda/data/utils/validate.py#L60
I wonder why and what would happen if I ignore this error.
Thanks in advance.

**Comment by maxjaritz** [comment]
Hi, SparseConvNet has maximum dimensions for the input coordinate grid, defined by the `full_scale` parameter. If you have points outside of `full_scale`, they will be discarded in the dataloader. When you predict the pseudo labels, it will check if you have valid labels for all points. Thus, if some points were discarded in the dataloader, because they were outside the `full_scale`, it throws an error. One easy way to solve it is to set the missing labels to ignore (`-100`).

**Comment by YukangWang** [comment]
Got it, thanks!
