### ISSUE TITLE
Selecting highly confident labels  for pseudo label generation

### ISSUE THREAD

**Issue by weiliuxm** [valeoai/xmuda#9]
Thank you for sharing the code.

The paper says 
>In details, once having optimized a model with Eq. 4, we extract pseudo-labels offline, selecting
highly confident labels based on the predicted class probability.

However,  I could not find how to select highly confident labels in validate.py.

**Comment by maxjaritz** [comment]
You are correct. In `validate.py` only the maximum probability and corresponding class label are saved to a .npy file. The label refinement is done when initializing the dataloader, using `xmuda/data/utils/refine_pseudo_labels.py`.

Best,
Max

**Comment by weiliuxm** [comment]
Thanks for the reply.

**Comment by taeyeopl** [comment]
Can you explain why you chose median operation as the highly confident label threshold instead of other options (mean, some threshold, topK)?? Or have you tried these experiments???
https://github.com/valeoai/xmuda/blob/8b39f8f77f048cd4c086323dd89fbf9710335d35/xmuda/data/utils/refine_pseudo_labels.py#L17
